spring:
  application:
    name: accountManager

  jpa:
    hibernate:
      ddl-auto: update

  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/accountManager?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


