spring:
  application:
    name: accountManager

  jpa:
    hibernate:
      ddl-auto: update

  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/accountManager?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: anshulgite2000@gmail.com
    password: zmcfwkpqrlikfeko
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


